name: Spack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
    - name: Unit test
      run: pytest test/unit_test.py
    - name: Integration test
      run: pytest test/integration_test.py
    - name: System test
      run: pytest test/system_test.py
